### ISSUE TITLE
Setup automated testing on the Mila / DRAC clusters

### ISSUE THREAD

**Issue by lebrice** [mila-iqia/ResearchTemplate#17]
## Requirements:
- When a PR is created and the workflows are approved by a member of IDT, the tests should be run in the following environments, stopping if any fail:
	1. GitHub CI (unit tests, CPU only)
	2. Self-hosted runner with a GPU (unit tests with GPU)
	3. Self-hosted runner with a GPU (integration tests with GPU)
	4. Self-hosted runner on the Mila cluster (unit tests)
	5. Self-hosted runner on the Mila cluster (integration tests)
	6. Self-hosted runner on (at least one of) the DRAC clusters, unit tests then integration tests.
- Track the test coverage and display it with a badge in the README

## Todos
There is a proof-of-concept for something like this in the `cluster-tests-ci` branch.
- [x] Setup a self-hosted runner on a dev machine with access to the Mila / DRAC clusters
- [x] Validate this idea with IT / Security / Infra
- [x] #24
- [x] #22
- [ ] Add instructions for forks of the template so setup their own self-hosted runners to do the same.
	- Ideally, the templating engine would ask questions such as "do you have an account on the Mila cluster?" and same for DRAC, and we could probably setup some (if not most) of the self-hosted runner stuff for them.
